# Generated by Django 3.2.15 on 2022-10-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_center_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
