# Generated by Django 3.2.15 on 2022-11-10 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20221104_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to='myapp.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 21, 32, 21, 147539, tzinfo=utc)),
        ),
    ]
