# Generated by Django 3.2.15 on 2022-11-10 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20221110_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
