# Generated by Django 3.2.15 on 2022-11-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='interested_in',
            field=models.ManyToManyField(blank=True, to='myapp.Category'),
        ),
    ]
